# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sign <- function(D) {
    .Call(`_mmdu_sign`, D)
}

dist_partial <- function(Theta, A) {
    .Call(`_mmdu_dist_partial`, Theta, A)
}

project_double <- function(x, C) {
    .Call(`_mmdu_project_double`, x, C)
}

project_vec <- function(a, C) {
    .Call(`_mmdu_project_vec`, a, C)
}

project_mat <- function(A, C) {
    .Call(`_mmdu_project_mat`, A, C)
}

lik_fn <- function(Theta, A, delta, Y, Omega) {
    .Call(`_mmdu_lik_fn`, Theta, A, delta, Y, Omega)
}

dt_fn <- function(Theta, A, delta, Y, Omega) {
    .Call(`_mmdu_dt_fn`, Theta, A, delta, Y, Omega)
}

da_fn <- function(Theta, A, delta, Y, Omega) {
    .Call(`_mmdu_da_fn`, Theta, A, delta, Y, Omega)
}

ut_fn <- function(Theta, A, delta, Y, Omega, M) {
    .Call(`_mmdu_ut_fn`, Theta, A, delta, Y, Omega, M)
}

ua_fn <- function(Theta, A, delta, Y, Omega, M) {
    .Call(`_mmdu_ua_fn`, Theta, A, delta, Y, Omega, M)
}

opti_fn <- function(Theta, A, delta, Y, Omega, M, tol = 1) {
    .Call(`_mmdu_opti_fn`, Theta, A, delta, Y, Omega, M, tol)
}

